version: '3'

services:
  bob-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERSIST_DIR=/app/whisky_embeddings
    volumes:
      - whisky_embeddings:/app/whisky_embeddings
    restart: unless-stopped

volumes:
  whisky_embeddings: 